BEGIN;
DROP VIEW crossed_over_resolved;
DROP TABLE crossed_over;
DROP VIEW tagged_resolved;
DROP TABLE tagged;
DROP VIEW authored_resolved;
DROP TABLE authored;
DROP TABLE fanfiction;
DROP TABLE lang;
DROP TABLE profile;
DROP TABLE author;
DROP TABLE related;
DROP TABLE tag_alias;
DROP TABLE tag;
DROP TABLE fandom;
DROP TABLE rating;
COMMIT;