BEGIN;
DROP TABLE crossed_over;
DROP TABLE tagged;
DROP TABLE authored;
DROP TABLE fanfiction;
DROP TABLE lang;
DROP TABLE profile;
DROP TABLE author;
DROP TABLE related;
DROP TABLE tag_alias;
DROP TABLE tag;
DROP TABLE fandom;
DROP TABLE rating;
COMMIT;